// <auto-generated />
namespace MvcOnlineTicariOtomasyon.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class change_added_satis : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_added_satis));
        
        string IMigrationMetadata.Id
        {
            get { return "202401051423332_change_added_satis"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
